spring.application.name=backend

server.port=${PORT:8080}

# Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=0

# JWT Secret Key
jwt.secret=${JWT_SECRET}

# File Upload Size
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB


#integrate Gemini API
gemini.api.key=aklfdlkjdkljdflkjdflkjd
