spring.application.name=backend

# Server Port
server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://mysql-13fa502-ai-resume-analyzer.l.aivencloud.com:10795/defaultdb?useSSL=true&requireSSL=true&sslMode=REQUIRED&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.data-source-properties.sslMode=REQUIRED

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=0





# JWT Secret Key
jwt.secret=VGhpc0lzTXlTdXBlclNlY3JldEtleUZvckp3dEF1dGhlbnRpY2F0aW9uMTIzNDU2

# File Upload Size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#integrate Gemini API
gemini.api.key=AIzaSyBtzeSYZLIdAAzF0PC0ohCGECVPs-88NkA
